name: Generate Swagger

on:
  workflow_dispatch: # 수동 실행

  push:
    tags: # 태그가 푸시될 때만 실행
      - "v*.*.*"

permissions:
  contents: write # 레포지토리 콘텐츠에 대한 쓰기 권한
  actions: read # 액션에 대한 읽기 권한
  pull-requests: write

jobs:
  update-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci # 의존성 설치

      - name: Run generate openapi specification
        run: npm run generate-openapi # OpenAPI 명세서를 생성

      - name: Validate OpenAPI specification
        run: |
          npm install -g swagger-cli
          swagger-cli validate dist/openapi.yaml # OpenAPI 명세서를 검증

      - name: Create Release
        uses: softprops/action-gh-release@v2 # GitHub Release를 생성하는 액션
        with:
          files: dist/openapi.yaml # 릴리즈에 포함할 파일
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Swagger UI for GitHub Pages
        run: |
          mkdir swagger-ui # Swagger UI를 위한 디렉토리 생성
          cp .github/swagger-index.html swagger-ui/index.html # Swagger UI를 위한 HTML 파일을 복사
          cp dist/openapi.yaml swagger-ui/ # Swagger UI가 API 명세서를 읽을 수 있도록 API 명세서 파일을 복사

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # GitHub Pages에 배포하는 액션
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub의 기본 인증 토큰
          publish_dir: ./swagger-ui # GitHub Pages에 배포할 디렉토리

